Feat/post topic
agile-learning-institute/mentorHub-topic-api pull request #21
Opened 2024-08-29 23:41 UTC by michquinn

2024-08-31 14:59 UTC, MyNameIsAndrew-Mangix commented on src/app/database.py
> +                    "_id": 0
Why are we excluding _id? I'm not as familiar with the topic codebase as I could be

2024-08-31 15:21 UTC, michquinn commented on src/app/database.py
> +                    "_id": 0
If you look at the `$set` instruction above it, you'll see it's just being replaced with `id`, a string representation of the OID (I'm trying to find where I documented the rationale, but I remember the PyMongo doesn't return a simple string representation by default either)

2024-08-31 15:39 UTC, FlatBallFlyer approved these changes
I believe the API Spec has the routes all ending with a / and that is also pretty consistent across other API's 

I'm not sure I like the approach of doing everything in main.py. I suggest you implement a logical separation of concerns. I don't care too much what the separations are, but if they aren't best practices you should document the logic behind your separation approach  in the README. I believe Flask best practices are:
``main.py`` or ``server.py`` - set everything up and start the server
``xxx_routes.py`` - `@app`. handlers for the xxx object
``xxx_services.py`` - Business logic (RBAC, validation, encode/decode, etc.) for the xxx object
``xxx_models.py`` - Database IO using ORM or other high level library. Your DB script kinda serves this role.

Note how this structure also isolates dependencies and supports unit testing.
 
I also think you should be using a more object oriented approach where possible, implementing proper unit testing is much easier when you are testing objects instead of scripts. Scripts tend to have abstract context that is confusing or difficult to initialize.

2024-08-31 15:39 UTC, FlatBallFlyer commented on src/app/database.py
> +                    "_id": 0
You should look at the services layer in the curriculum-api - there I have a "stringily" function that recursively crawls a dictionary stringifying all ObjectID and DateTime values. I felt like my MongoIO calls were getting complicated enough, and doing it in code seemed pretty easy. Especially since there will also be an "encoding" function that is needed in the other direction.

2024-08-31 15:40 UTC, FlatBallFlyer requested changes
Approved by mistake, and I don't know how to "un-approve" it - should have marked it "Changed Requested"

2024-08-31 16:42 UTC, michquinn commented
> I believe the API Spec has the routes all ending with a /
If you're talking about the spec for this API, it does not. Nor do any of the following:
- The [Petstore swagger API](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml) sample
- The API examples from [stepci's documentation](https://docs.stepci.com/guides/testing-http.html)
- [Stripe](https://docs.stripe.com/api)'s API
- Google's API [style guide](https://cloud.google.com/apis/design/resources#examples)
- Prometheus's [API](https://prometheus.io/docs/prometheus/latest/querying/api/#config)
- Grafana's [API](https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/public/openapi3.json)

But if you need the code to handle either case, that can be done

2024-08-31 16:49 UTC, michquinn commented on src/app/database.py
> +                    "_id": 0
Keep in mind, Pymongo doesn't return a Python `ObjectID`, but EJSON, so that wouldn't work

2024-08-31 23:33 UTC, FlatBallFlyer commented on src/app/database.py
> +                    "_id": 0
This works, just how I'm handling it
```py
 def _stringify_mongo_types(self, document):
        """Recursively convert ObjectId and datetime values to strings in a dictionary."""
        if isinstance(document, dict):
            return {
                key: self._stringify_mongo_types(value) for key, value in document.items()
            }
        elif isinstance(document, list):
            return [self._stringify_mongo_types(item) for item in document]
        elif isinstance(document, ObjectId):
            return str(document)
        elif isinstance(document, datetime):
            return document.isoformat()
        else:
            return document        
```

2024-09-01 12:51 UTC, michquinn commented on src/app/database.py
> +                    "_id": 0
Fixed in 8512759

2024-10-21 01:20 UTC, closed without merging